apparently stderr was not the correct place to write to

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -75,12 +75,13 @@ deploy:maven-latest:
     expire_in: 7 days
   script:
     # Heads up - all whitespace in here is a space. There are no newlines. Use semicolons
-    # >2 is std-error
-    - if [ -z "$SE_ARTIFACTORY_PASSWORD" ]; then 
-      echo >2 WARNING!!! COULD NOT READ THE DEPLOY PASSWORD;
-      echo >2 the deploy password is stored in a protected variable, and your deploy will fail if we cannot read it;
+    - if [ -z "$SE_ARTIFACTORY_PASSWORD" ]; then
+      echo  WARNING!!! COULD NOT READ THE DEPLOY PASSWORD;
+      echo  the deploy password is stored in a protected variable, and your deploy will fail if we cannot read it;
+      exit 1
       elif [ ! -f ci_settings.xml ]; then
-      echo >2 "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for instructions.";
+      echo  "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for instructions.";
+      exit 1
       else
       mvn $MAVEN_CLI_OPTS deploy --settings ci_settings.xml;
       fi
